# dvc.yaml

vars:
  - params.yaml: [data_splits, gold_pipeline]

stages:
  split_data:
    cmd: python src/data_split/split_data.py
    deps:
      - src/data_split/split_data.py
      - src/shared/
      - src/data_ingestion/data_loader.py
      - data/raw/flights.csv
    outs:
      - data/raw/train_validation_test/train.csv
      - data/raw/train_validation_test/validation.csv
      - data/raw/train_validation_test/test.csv

  bronze_pipeline:
    foreach: ${data_splits}
    do:
      cmd: python src/pipelines/bronze_pipeline.py ${item}.csv
      deps:
        - src/pipelines/bronze_pipeline.py
        - src/shared/
        # --- Specific GE Dependencies ---
        - src/data_validation/ge_components.py
        - src/data_validation/expectations/bronze_expectations.py
        - data/raw/train_validation_test/${item}.csv
      outs:
        - data/bronze_data/processed/${item}.csv

  silver_pipeline:
    foreach: ${data_splits}
    do:
      cmd: python src/pipelines/silver_pipeline.py ${item}.csv
      deps:
        - src/pipelines/silver_pipeline.py
        - src/data_ingestion/
        - src/silver_data_preprocessing/
        - src/shared/
        # --- Specific GE Dependencies ---
        - src/data_validation/ge_components.py
        - src/data_validation/expectations/silver_expectations.py
        - data/bronze_data/processed/${item}.csv
      outs:
        - data/silver_data/processed/${item}.parquet

  gold_pipeline:
    cmd: python src/pipelines/gold_pipeline.py
    deps:
      - src/pipelines/gold_pipeline.py
      - src/gold_data_preprocessing/
      - src/data_ingestion/
      - src/shared/
      - data/silver_data/processed/train.parquet
      - data/silver_data/processed/validation.parquet
      - data/silver_data/processed/test.parquet
    params:
      - gold_pipeline.imputation
      - gold_pipeline.rare_category_grouping
      - gold_pipeline.outlier_handling
      - gold_pipeline.power_transformer
    outs:
      - data/gold_engineered_data/processed/train.parquet
      - data/gold_engineered_data/processed/validation.parquet
      - data/gold_engineered_data/processed/test.parquet
      - models/simple_imputer.json
      - models/rare_category_grouper.joblib
      - models/categorical_encoder.joblib
      - models/outlier_handler.joblib
      - models/power_transformer.joblib
      - models/scaler.joblib
