name: travels_mlops
channels:
  - defaults
dependencies:
  - python=3.12.9
  - pandas=2.1.4
  - numpy=1.26.4
  - scikit-learn=1.7.0
  - pyyaml=6.0.1
  - openpyxl=3.1.5
  - pytest=8.4.1
  - pip
  - pip:
      - great-expectations==1.5.5
      - python-json-logger==2.0.7
