site_name: Flight Prices
site_url: https://mydomain.org/Flights_Price_Prediction_MLOPS
site_description: "MLOps project for flight price prediction."
site_author: "Daksh Vanshaj"

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    # Palette toggle for dark mode (now the default)
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  primary: teal
  accent: amber
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.instant
    - content.code.annotate
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

nav:
  - Home: index.md
  - Data Journey:
      - "Exploratory Data Analysis": EDA/flights_eda.ipynb
      - "Automated EDA Report": EDA/flights_training_eda_report.html
      - "Data Pipelines":
          - Data Architecture: Data Pipelines/data_pipelines.md
          - Bronze Pipeline: Data Pipelines/bronze_pipeline.md
          - Silver Pipeline: Data Pipelines/silver_pipeline.md
          - Gold Pipeline: Data Pipelines/gold_pipeline.md
  - Modeling:
      - "Training & Evaluation Pipeline": Modeling/training_pipeline.md
      - "HyperParameter Tuning Pipeline": Modeling/tuning_pipeline.md
      - "Model Selection & Evaluation": Modeling/model_selection_report.md
      - "Model Explanability (Champion)": Modeling/model_explainability_lgbm_champ.md
      - "Model Comparison (Archived)": Modeling/model_explainability_lgbm_vs_xgb.md

  - Production Model Guide:
      - "LightGBM Details": LGBM_summary/LGBMR_production_model_details.md
  - API:
      - "API Reference": API/api_reference.md
  - MLOps:
      - "Project Architecture": MLOps/architecture.md
      - "Tooling": MLOps/tools.md

repo_url: https://github.com/dakshvanshaj/Flights-Price--Prediction-MLOPs
repo_name: Flights-Price-Prediction-MLOPs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dakshvanshaj

copyright: Copyright &copy; 2025 Daksh Vanshaj
