name: CI - Validate Project Integrity

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-extras --locked
          uv pip install .
      # uv pip sync requirements.lock --system
      - name: Lint with Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Execute Pytest Suite
        env:
          PYTHONPATH: src
        run: |
          pytest

  validate_dvc_pipeline:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.3"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --all-extras --locked
          uv pip install .

      - name: Configure AWS Credentials for MLflow
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MLFLOW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MLFLOW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MLFLOW_AWS_DEFAULT_REGION }}

      - name: Configure DVC Remote for Backblaze B2
        env:
          DVC_REMOTE_NAME: ${{ secrets.DVC_REMOTE_NAME }}
          DVC_S3_ENDPOINT_URL: ${{ secrets.DVC_S3_ENDPOINT_URL }}
          DVC_S3_ENDPOINT_REGION: ${{ secrets.DVC_S3_ENDPOINT_REGION }}
          B2_ACCESS_KEY_ID: ${{ secrets.B2_ACCESS_KEY_ID }}
          B2_SECRET_ACCESS_KEY: ${{ secrets.B2_SECRET_ACCESS_KEY }}
        run: |
          dvc remote modify --local "$DVC_REMOTE_NAME" endpointurl "$DVC_S3_ENDPOINT_URL"
          dvc remote modify --local "$DVC_REMOTE_NAME" region "$DVC_S3_ENDPOINT_REGION"
          dvc remote modify --local "$DVC_REMOTE_NAME" access_key_id "$B2_ACCESS_KEY_ID"
          dvc remote modify --local "$DVC_REMOTE_NAME" secret_access_key "$B2_SECRET_ACCESS_KEY"

      - name: Pull DVC Data
        run: |
          dvc pull

      - name: Reproduce DVC Pipeline
        env:
          PYTHONPATH: src
        run: |
          dvc repro

  build_prediction_server:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build Docker Image
        run: |
          docker build -f src/prediction_server/Dockerfile -t prediction-server:ci .
