name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy Documentation
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0 # Needed for mkdocs-material to get git history for last updated feature

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.12"

            - name: Install uv
              run: pip install uv

            - name: install dependencies
              run: |
                  uv sync --all-extras --locked
                  uv pip install -e .

            - name: Deploy with MkDocs
              run: uv run mkdocs gh-deploy --force
